# Generated by Django 3.0.2 on 2020-02-05 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bisheapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rootuser',
            name='ifroot',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ifroot',
        ),
    ]
