# Generated by Django 2.0.6 on 2020-02-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bisheapp', '0003_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='create_time',
            field=models.CharField(max_length=128, verbose_name='创建时间'),
        ),
    ]
